# -*- coding: utf-8 -*-
"""IISC.n.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H91typN6Le7gQtjt507EOyvWZ9KiviGC
"""

! pip install ultralytics



!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="FTdwXCoY4fZeOhQZhtwj")
project = rf.workspace("street-lightv").project("street-light-3-wt5ha")
version = project.version(2)
dataset = version.download("yolov8")

from ultralytics import YOLO
model = YOLO("yolov8n.pt")  # Or yolov8s.pt / yolov8m.pt / yolov8l.pt / yolov8x.pt

results = model.train(
    data="/content/Street-light-3-2/data.yaml",
    epochs=10,
    batch=16,
    name="yolo-roboflow-training"
)