# -*- coding: utf-8 -*-
"""yolo_seg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14KMeQPlLUNiXNpNwmNP77OWX0oJPYUV1
"""

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="FTdwXCoY4fZeOhQZhtwj")
project = rf.workspace("street-lightv").project("night-road-zwyjj")
version = project.version(3)
dataset = version.download("yolov8")

!pip install ultralytics

from ultralytics import YOLO

# Step 3: Load YOLOv8 segmentation model (pretrained)
model = YOLO("yolov8n-seg.pt")  # n=smallest, also try yolov8s-seg.pt for better accuracy

# Step 4: Train on your dataset
model.train(
    data=f"{dataset.location}/data.yaml",  # roboflow provides this
    epochs=20,
    imgsz=512,
    batch=2
)